### ISSUE TITLE
Event Object "from" and "to" always same value

### ISSUE THREAD

**Issue by gabbyvan** [williamtroup/Calendar.js#89] opened 2022-11-23 21:41 UTC
Event Object "from" and "to" is always setting to the date value of the "from" date if events are parsed from the server as json object array

**Comment by williamtroup** [comment] 2022-11-29 14:55
Hi.  I will take a look into this issue.  Thanks.

**Comment by williamtroup** [comment] 2023-03-30 17:49
After going through this in testing, using multiple browsers and environments, I've been unable to reproduce this problem.  I'm going to close this issue, but if you supply some JSON and let me know which public method you calling to add the events, I will reactivate it.

**Closed by williamtroup** 2023-03-30 17:49 UTC
